[project]
name = "volff"
version = "0.1.0"
description = "Statistical rendering experiments"
readme = "README.md"
requires-python = "~=3.13.0"
dependencies = [
    "numpy",
    "pillow",
    "rich",
    "slangpy>=0.31.0",
    "torch>=2.0",
    "torchvision",
    "typer",
    "diffusers",
    "einops",
    "accelerate",
    "scipy",
    "deepspeed",
    "mpi4py"
]

[project.scripts]
volff = "volff.cli.main:main"

[tool.uv]
